config:
  install_tree:
    root: @@SPACK_INSTALL_ROOT@@/2026/annual/opt
  build_stage:
  - @@SPACK_INSTALL_ROOT@@/2026/annual/stage
  source_cache: @@SPACK_INSTALL_ROOT@@/cache/source
  misc_cache: @@SPACK_INSTALL_ROOT@@/2026/annual/cache
