#!/usr/bin/env bash
# Renders this year's control-plane templates against a concrete install
# root, and writes an init script that sets the environment needed to run
# spack/module commands against this year fully self-contained (nothing
# touches $HOME).
#
# This script is git-tracked control-plane tooling, isolated per year
# (control/<year>/bootstrap.sh, not a shared control/bootstrap.sh) -- so
# its behavior (like spack/ and meta/) is free to change incompatibly
# from one year to the next. The year itself is inferred from its own
# location (one level up), not passed as an argument.
#
# The generated init script it writes, by contrast, is install-root
# output -- not git-tracked, regenerated by this script, tied to whatever
# concrete install root you point it at.
#
# Two template trees are rendered, with different output rules:
#
#   templates/...          ->  <install-root>/<year>/...
#     (Spack config: config.yaml, upstreams.yaml, modules.yaml.
#     Namespaced under the year so different years never collide.)
#
#   meta/templates/<tier>.lua  ->  <install-root>/modules/meta/<year>/<tier>.lua
#     (Lmod meta-modules. Rendered to a *stable* path that doesn't move
#     between years, so `module use <install-root>/modules/meta` never
#     has to change and `module load <year>/<tier>` keeps resolving the
#     way Lmod expects.)
#
# In both cases the placeholder @@SPACK_INSTALL_ROOT@@ is replaced with
# the literal install root, so nothing downstream (spack invocations,
# Lmod module loads) ever needs SPACK_INSTALL_ROOT set.
#
# It also writes <install-root>/<year>/bin/init.sh, which exports
# SPACK_DISABLE_LOCAL_CONFIG and SPACK_USER_CACHE_PATH (namespaced per
# year, so a different year's Spack version never shares a bootstrap
# store with this one) -- source it before running spack or module
# commands against this year, instead of exporting those by hand.
#
# Usage: control/<year>/bootstrap.sh <install-root-path>
#
# Idempotent: re-run after editing a template, adding a tier, or switching
# to a different install root (e.g. a new scratch disk) -- it just
# overwrites the previously rendered files for this year.
#
# This script only reads control/<year>/ and writes under the given
# install root. It does not touch $HOME, /etc, or any other system path,
# and it does not invoke spack, clone anything, or install any software.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "usage: $0 <install-root-path>" >&2
  exit 1
fi

install_root="$1"
year_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
year="$(basename "$year_dir")"
placeholder="@@SPACK_INSTALL_ROOT@@"

mkdir -p "$install_root"

# Spack config: mirror relative path under <install-root>/<year>/.
if [ -d "$year_dir/templates" ]; then
  find "$year_dir/templates" -type f | while IFS= read -r tmpl; do
    rel="${tmpl#"$year_dir/templates/"}"
    dst="$install_root/$year/$rel"
    mkdir -p "$(dirname "$dst")"
    sed "s|$placeholder|$install_root|g" "$tmpl" > "$dst"
    echo "rendered $year/$rel"
  done
fi

# Meta-modules: flatten into <install-root>/modules/meta/<year>/<file>,
# regardless of how the meta/ tree itself is organized internally.
if [ -d "$year_dir/meta/templates" ]; then
  find "$year_dir/meta/templates" -type f | while IFS= read -r tmpl; do
    name="$(basename "$tmpl")"
    dst="$install_root/modules/meta/$year/$name"
    mkdir -p "$(dirname "$dst")"
    sed "s|$placeholder|$install_root|g" "$tmpl" > "$dst"
    echo "rendered modules/meta/$year/$name"
  done
fi

# Init script: generated, not git-tracked -- lives under the install
# root's own bin/, source it before running spack or module commands
# against this year.
init_script="$install_root/$year/bin/init.sh"
mkdir -p "$(dirname "$init_script")"
cat > "$init_script" <<EOF
# Source this before running spack or module commands against the $year
# tier of this stack. Do not execute it directly -- it only takes effect
# in the shell that sources it:
#   source $init_script
export SPACK_DISABLE_LOCAL_CONFIG=1
export SPACK_USER_CACHE_PATH="$install_root/$year/user-cache"
EOF
echo "wrote $year/bin/init.sh"
